### ISSUE TITLE
[DEVOPS] Como liberar releases diferentes por TenantId?

### ISSUE THREAD

**Issue by cristofersousa** [opensanca/forum#2]
## Contexto

Já vi algumas perguntas aleatórias sobre isso e não tenho ideia de como funciona, no caso existem empresas que liberam uma determinada release para um grupo de cliente específico, e existem clientes que não querem ser migrados pois preferem o modelo antigo.  Nesse caso, como é feito esse gerenciamento de releases pensando em algo que tenha uma qualidade de vida na entrega? 

## Referências 
  
0. [Github Artigo](https://docs.github.com/pt/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository)
1. [Treinaweb Artigo](https://www.treinaweb.com.br/blog/criando-release-no-github/)

**Comment by andrelugomes** [comment]
Acho que o caminho não é versionando o software por cliente.

E sim controle de acessos dentro do app.
